/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package irrigationdashboard;

import controller.Controller;
import java.beans.PropertyChangeEvent;
import moisturesensor.MoistureSensor;

/**
 *
 * @author giacomodeliberali
 */
public class DashboardPanel extends javax.swing.JPanel {

    public Controller controller = new Controller();
    public MoistureSensor sensor = new MoistureSensor();

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        bindController();
    }

    private void bindController() {

        humididyLabel.setText("" + sensor.getCurrentHumidity());
        decreasingLabel.setText(sensor.isDecreasing() ? "Yes" : "No");

        sensor.addPropertyChangeListener(MoistureSensor.CURRENT_HUMIDITY_CHANNEL, (PropertyChangeEvent evt) -> {
            int humididy = (int) evt.getNewValue();
            controller.setLocHumididy(humididy);
            humididyLabel.setText("" + humididy);
        });

        sensor.addPropertyChangeListener(MoistureSensor.DECREASING_CHANNEL, (PropertyChangeEvent evt) -> {
            boolean decreasing = (boolean) evt.getNewValue();
            decreasingLabel.setText(decreasing ? "Yes" : "No");
        });

        controller.addPropertyChangeListener(Controller.ON_CHANNEL, (PropertyChangeEvent evt) -> {
            boolean isOn = (boolean) evt.getNewValue();
            sensor.setDecreasing(!isOn);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controller1 = new controller.Controller();
        moistureSensor1 = new moisturesensor.MoistureSensor();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        humididyLabel = new javax.swing.JLabel();
        decreasingLabel = new javax.swing.JLabel();

        jLabel1.setText("Humidity:");

        jLabel2.setText("Decreasing:");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        humididyLabel.setText("None");

        decreasingLabel.setText("None");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decreasingLabel)
                    .addComponent(humididyLabel))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(humididyLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(decreasingLabel))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if (!sensor.isStarted()) {
            sensor.start();
            startButton.setText("Stop");
        } else {
            sensor.stop();
            startButton.setText("Start");
        }
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controller.Controller controller1;
    private javax.swing.JLabel decreasingLabel;
    private javax.swing.JLabel humididyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private moisturesensor.MoistureSensor moistureSensor1;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
